services:
  bookstack:
    image: lscr.io/linuxserver/bookstack
    container_name: bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - APP_URL=http://195.90.228.116:6875
      - DB_HOST=bookstack_db
      - DB_USER=bookstack
      - DB_PASS=myMariaDBpass
      - DB_DATABASE=bookstackapp
    volumes:
      - /config:/config
    ports:
      - 6875:80
    restart: unless-stopped
    depends_on:
      - bookstack_db
  bookstack_db:
    image: lscr.io/linuxserver/mariadb
    container_name: bookstack_db
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=MyRo0tpassword
      - TZ=Europe/Berlin
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=myMariaDBpass
    volumes:
      - /config:/config
    restart: unless-stopped
